In [27]:
import torch
import torch.nn as nn

In [51]:
mx = torch.arange(1,5,dtype=torch.float).view(1,1,2,2)
mx

tensor([[[[1., 2.],
          [3., 4.]]]])

In [47]:
fi = nn.Upsample(scale_factor=2, mode='nearest')
fi(mx)

tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [3., 3., 4., 4.],
          [3., 3., 4., 4.]]]])

In [34]:
fi = nn.Upsample(scale_factor=2, mode='bilinear')
fi(mx)

tensor([[[[1.0000, 1.2500, 1.7500, 2.0000],
          [1.5000, 1.7500, 2.2500, 2.5000],
          [2.5000, 2.7500, 3.2500, 3.5000],
          [3.0000, 3.2500, 3.7500, 4.0000]]]])

In [35]:
fi = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
fi(mx)

tensor([[[[1.0000, 1.3333, 1.6667, 2.0000],
          [1.6667, 2.0000, 2.3333, 2.6667],
          [2.3333, 2.6667, 3.0000, 3.3333],
          [3.0000, 3.3333, 3.6667, 4.0000]]]])

In [52]:
fi = nn.Upsample(scale_factor=2, mode='bicubic', align_corners=True)
fi(mx)

tensor([[[[1.0000, 1.3148, 1.6852, 2.0000],
          [1.6296, 1.9444, 2.3148, 2.6296],
          [2.3704, 2.6852, 3.0556, 3.3704],
          [3.0000, 3.3148, 3.6852, 4.0000]]]])

In [49]:
mx = torch.arange(1,5,dtype=torch.float).view(1,2,2)
fi = nn.Upsample(scale_factor=2, mode='linear')
fi(mx)

tensor([[[1.0000, 1.2500, 1.7500, 2.0000],
         [3.0000, 3.2500, 3.7500, 4.0000]]])